In [1]:
import pandas as pd
import numpy as np


In [2]:
df_products = pd.read_csv('Downloads/products_df.csv')

In [3]:
df_products

Unnamed: 0   pk_cid pk_partition  short_term_deposit  loans  \
0                 0  1375586   2018-01-28                   0      0   
1                 1  1050611   2018-01-28                   0      0   
2                 2  1050612   2018-01-28                   0      0   
3                 3  1050613   2018-01-28                   1      0   
4                 4  1050614   2018-01-28                   0      0   
...             ...      ...          ...                 ...    ...   
5962919    13647304  1166765   2019-05-28                   0      0   
5962920    13647305  1166764   2019-05-28                   0      0   
5962921    13647306  1166763   2019-05-28                   0      0   
5962922    13647307  1166789   2019-05-28                   0      0   
5962923    13647308  1550586   2019-05-28                   0      0   

         mortgage  funds  securities  long_term_deposit  em_account_pp  \
0               0      0           0                  0              0   
1               0      0           0                  0              0   
2               0      0           0                  0              0   
3               0      0           0                  0              0   
4               0      0           0                  0              0   
...           ...    ...         ...                ...            ...   
5962919         0      0           0                  0              0   
5962920         0      0           0                  0              0   
5962921         0      0           0                  0              0   
5962922         0      0           0                  0              0   
5962923         0      0           0                  0              0   

         credit_card  payroll  pension_plan  payroll_account  emc_account  \
0                  0      0.0           0.0                0            0   
1                  0      0.0           0.0                0            0   
2                  0      0.0           0.0                0            0   
3                  0      0.0           0.0                0            0   
4                  0      0.0           0.0                0            0   
...              ...      ...           ...              ...          ...   
5962919            0      0.0           0.0                0            0   
5962920            0      0.0           0.0                0            0   
5962921            0      0.0           0.0                0            0   
5962922            0      0.0           0.0                0            0   
5962923            0      0.0           0.0                0            0   

         debit_card  em_account_p  em_acount  
0                 0             0          1  
1                 0             0          1  
2                 0             0          1  
3                 0             0          0  
4                 0             0          1  
...             ...           ...        ...  
5962919           0             0          1  
5962920           0             0          1  
5962921           0             0          1  
5962922           0             0          1  
5962923           0             0          1  

[5962924 rows x 18 columns]

Ejercicio 1

In [4]:
df_products['credit_card'].describe()

count    5.962924e+06
mean     1.188444e-02
std      1.083660e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.000000e+00
Name: credit_card, dtype: float64

Ejercicio 3

In [5]:
df2 = df_products.iloc[:, 0:2]

In [6]:
df2.shape

(5962924, 2)

Ejercicio 4

In [7]:
import numpy as np

np.random.seed(10)

# generating 10 random values for each of the two variables
X = np.random.randn(10)

Y = np.random.randn(10)

# computing the corrlation matrix
C = np.corrcoef(X,Y)

print(C)

[[1.         0.37258014]
 [0.37258014 1.        ]]


El valor es entre 1 y 0. Cuanto más cercano ,sea al valor 1, mayor correlación hay, entre ambas variables; hay que\
excluir los 1 de la matriz identidad, que corresponden a 1. En este caso, hay una correlacion entre ambas variables de\
un 37%, con lo que concluimos, que NO, hay una gran correlacion entre ambas variables

Ejercicio 2

In [8]:
a =100* np.random.random((10,10))

In [9]:
a

array([[44.18331744, 43.40139933, 61.77669785, 51.31382426, 65.03971819,
        60.10389534, 80.52231968, 52.16471524, 90.86488808, 31.9236089 ],
       [ 9.04593493, 30.07000566, 11.39843619, 82.86813263,  4.68963194,
        62.62871483, 54.75861559, 81.92869957, 19.89475397, 85.68503025],
       [35.16526394, 75.46476915, 29.59617069, 88.39364796, 32.55116378,
        16.50158977, 39.25292439,  9.34603746, 82.11056578, 15.11520196],
       [38.41144487, 94.42607122, 98.76254749, 45.63045471, 82.61228438,
        25.13741342, 59.73716482, 90.28317603, 53.45579488, 59.0201363 ],
       [ 3.92817672, 35.71817586,  7.96130902, 30.54599183, 33.0719312 ,
        77.38302962,  3.99592087, 42.94921784, 31.49268718, 63.64911431],
       [34.63471501,  4.30973562, 87.99151745, 76.32405871, 87.80966427,
        41.75091438, 60.55775644, 51.34666274, 59.7836648 , 26.22156611],
       [30.08713089,  2.53997821, 30.30625607, 24.20758754, 55.75781887,
        56.55070199, 47.51322474, 29.27979763

In [10]:
a.round(0)

array([[44., 43., 62., 51., 65., 60., 81., 52., 91., 32.],
       [ 9., 30., 11., 83.,  5., 63., 55., 82., 20., 86.],
       [35., 75., 30., 88., 33., 17., 39.,  9., 82., 15.],
       [38., 94., 99., 46., 83., 25., 60., 90., 53., 59.],
       [ 4., 36.,  8., 31., 33., 77.,  4., 43., 31., 64.],
       [35.,  4., 88., 76., 88., 42., 61., 51., 60., 26.],
       [30.,  3., 30., 24., 56., 57., 48., 29.,  6., 98.],
       [34., 50., 98., 44., 32., 52., 58., 85.,  7., 46.],
       [78., 72., 59.,  4., 35., 56., 30., 51., 67., 16.],
       [ 5., 34., 11., 18., 89., 37., 22., 75., 11., 74.]])

In [11]:
a.shape

(10, 10)